# Week 3 Assignment
* Download the "Week_3_Assignment.ipynb" notebook 
* Fill in the code in the cells marked with `# YOUR ANSWER HERE:` by answering the question/task defined in the cell above it starting with `GRADED:`
* Code cells outside of `# YOUR ANSWER HERE:` will not be considered for grading. 
  * Feel free to write outside of it for debugging
* Submit the updated notebook
  * Make sure to save your changes before submitting it!

In [3]:
# PLEASE, DO NOT MODIFY THIS CELL!

# IMPORT NECESSARY LIBRARIES AND DATA
import pandas as pd
import numpy as np

# SECtION A data
nparr = np.arange(145, 217).reshape(12, 6)

# data location
data_url = 'https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv'
a_df = pd.read_csv(data_url, header=0)
a_df.head()


iata                            airport               city state country  \
0  ORD       Chicago O'Hare International            Chicago    IL     USA   
1  ATL  William B Hartsfield-Atlanta Intl            Atlanta    GA     USA   
2  DFW    Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   
3  PHX   Phoenix Sky Harbor International            Phoenix    AZ     USA   
4  DEN                        Denver Intl             Denver    CO     USA   

         lat        long    cnt  
0  41.979595  -87.904464  25129  
1  33.640444  -84.426944  21925  
2  32.895951  -97.037200  20662  
3  33.434167 -112.008056  17290  
4  39.858408 -104.667002  13781

## GRADED SECTION A

1. Determine the shape, number of dimensions and type of elements in the numpy array `nparr`
2. Determine the standard deviation of all elements in `nparr`
3. Determine the position (not the value) of the maximum value element in `nparr`
4. Create an array of the same shape as `nparr` but filled with zeros
5. Create an array of the same shape as `nparr` but filled with ones
6. Create an array of the same shape as `nparr` but where all elements are the square root values
7. Create an array result of shape `12` by `12` resulting from multiplication of nparr with transpose(`nparr`). Hint: use `np.dot`

In [5]:
# YOUR SECTION A ANSWER HERE (please use comments to number each of your answers)
# 1. Determine the shape, number of dimensions, and type of elements in nparr
shape = nparr.shape
dimensions = nparr.ndim
element_type = nparr.dtype

print("Shape:", shape)
print("Number of dimensions:", dimensions)
print("Type of elements:", element_type)

# 2. Determine the standard deviation of all elements in nparr
std_dev = np.std(nparr)
print("Standard deviation of elements in nparr:", std_dev)

# 3. Determine the position of the maximum value element in nparr
max_position = np.unravel_index(nparr.argmax(), nparr.shape)
print("Position of maximum value element:", max_position)

# 4. Create an array of zeros with the same shape as nparr
zeros_arr = np.zeros_like(nparr)
print("Array of zeros with the same shape as nparr:\n", zeros_arr)

# 5. Create an array of ones with the same shape as nparr
ones_arr = np.ones_like(nparr)
print("Array of ones with the same shape as nparr:\n", ones_arr)

# 6. Create an array with square root values and the same shape as nparr
sqrt_arr = np.sqrt(nparr)
print("Array with square root values of nparr:\n", sqrt_arr)

# 7. Create an array resulting from the multiplication of nparr with its transpose
result = np.dot(nparr, nparr.T)
print("Result of multiplication of nparr with its transpose:\n", result)


Shape: (12, 6)
Number of dimensions: 2
Type of elements: int32
Standard deviation of elements in nparr: 20.7826049057058
Position of maximum value element: (11, 5)
Array of zeros with the same shape as nparr:
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
Array of ones with the same shape as nparr:
 [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Array with square root values of nparr:
 [[12.04159458 12.08304597 12.12435565 12.16552506 12.20655562 12.24744871]
 [12.28820573 12.32882801 12.36931688 12.40967365 12.4498996  12.489996  ]
 [12.52996409 12.56980509 12.60952021 12.64911064 12.68857754 12.72792206]
 [12.76714533 12.80624847 12.84523258 12.88409873 12.92284798 12.9614814 ]
 [13.         13.03840481 13.07669683 13.1

## GRADED SECTION B

The dataframe `a_df` loads the dataset that contains information on a number of categories regarding traffic (variable `cnt` represents the actual traffic) at US airports from February 2011.
The dataset has already been loaded for you in the first code cell above.
 1. Print the number of rows for the subset of the dataframe for which traffic values are higher than `10,000` (ideally, you should format the print to put the thousands comma separator--as in `23,400` instead of `23400`
 2. Print the names of all the columns of the dataframe
 3. Print a subset of the dataframe containing the `10th` and the `3rd` rows of the original dataframe (`in that order`).
 4. Which US `state` has the `8th` largest __total__ airport traffic? Please, make sure you use the correct variable as described above.
 5. Which state has the second-most __total__ number of airports (i.e. the second-most amount of airports)?
 6. Of the cities that have multiple airports, which one has the least total traffic for all airports?
 7. What is the total airport traffic for all states that border the state of Massachusetts?


In [6]:
# YOUR SECTION B ANSWER HERE (please use comments to number each of your answers)
# 1. Print the number of rows where traffic values are higher than 10,000:
high_traffic_rows = a_df[a_df['cnt'] > 10000]
num_high_traffic_rows = high_traffic_rows.shape[0]
print(f"Number of rows with traffic > 10,000: {num_high_traffic_rows:,}")

# 2. Print the names of all the columns in the DataFrame:
column_names = a_df.columns
print("Column names:")
for column in column_names:
    print(column)

# 3. Print a subset of the DataFrame containing the 10th and 3rd rows:
subset_10th_3rd_rows = a_df.iloc[[9, 2]]
print("Subset of 10th and 3rd rows:")
print(subset_10th_3rd_rows)

# 4. Identify the state with the 8th largest total airport traffic:
state_8th_largest_traffic = a_df.groupby('state').sum().nlargest(8, 'cnt').tail(1)
print("State with the 8th largest total airport traffic:", state_8th_largest_traffic.index[0])

# 5. Identify the state with the second-most total number of airports:
state_second_most_airports = a_df['state'].value_counts().nlargest(2).index[1]
print("State with the second-most total number of airports:", state_second_most_airports)

# 6. Find the city with the least total traffic among cities with multiple airports:
city_least_traffic_multiple_airports = a_df.groupby('city')['cnt'].sum()[a_df['city'].value_counts() > 1].nsmallest(1)
print("City with the least total traffic among cities with multiple airports:", city_least_traffic_multiple_airports.index[0])

# 7. Calculate the total airport traffic for all states bordering Massachusetts:
bordering_states = ['NH', 'VT', 'NY', 'CT', 'RI']
traffic_bordering_MA = a_df[a_df['state'].isin(bordering_states)]['cnt'].sum()
print("Total airport traffic for states bordering Massachusetts:", traffic_bordering_MA)

Number of rows with traffic > 10,000: 10
Column names:
iata
airport
city
state
country
lat
long
cnt
Subset of 10th and 3rd rows:
  iata                          airport               city state country  \
9  CLT  Charlotte/Douglas International          Charlotte    NC     USA   
2  DFW  Dallas-Fort Worth International  Dallas-Fort Worth    TX     USA   

         lat       long    cnt  
9  35.214011 -80.943126  10490  
2  32.895951 -97.037200  20662  
State with the 8th largest total airport traffic: CO
State with the second-most total number of airports: TX
City with the least total traffic among cities with multiple airports: Charleston
Total airport traffic for states bordering Massachusetts: 22007


C:\Users\kvsns\AppData\Local\Temp\ipykernel_14352\137683880.py:19: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  state_8th_largest_traffic = a_df.groupby('state').sum().nlargest(8, 'cnt').tail(1)
